export default function generateMetadata() {
  const title = "Windows 10 UI Clone - Interactive Portfolio by Yonas"
  const description =
    "An interactive portfolio website designed as a Windows 10 desktop clone. Explore projects, skills, and professional information through a familiar Windows 10 interface."
  const url = "https://portfolio.yonas.com"
  const ogImage = "https://portfolio.yonas.com/images/og-image.png"

  return {
    title,
    description,
    metadataBase: new URL(url),
    openGraph: {
      title,
      description,
      url,
      siteName: "Yonas Portfolio",
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: "Windows 10 UI Clone Portfolio",
        },
      ],
      locale: "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImage],
      creator: "@yonas",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: url,
    },
    authors: [{ name: "Yonas Kassahun", url: "https://github.com/yonas-star" }],
    creator: "Yonas kassahun",
    publisher: "yonas",
    keywords: [
      "portfolio",
      "windows 10",
      "ui clone",
      "web developer",
      "react",
      "next.js",
      "interactive portfolio",
      "yonas",
      "kassahun",
      "yonas kassahun",
      "software engineer",
      "web designer",
      "javascript",
      "typescript",
      "css",
      "html",
      "personal website",
      "projects",
      "skills",
      "professional portfolio",
      "responsive design",
      "modern web development",
      "tech portfolio",
      "coding portfolio",
      "software development",
      "programming",
      "tech skills",
      "web applications",
      "ui/ux design",
      "user interface",
      "user experience",
      "dev portfolio",
      "software projects",
      "tech stack",
      "development skills",
      "web technologies",
      "frontend development",
      "backend development",
      "full stack development",
      "nextjs portfolio",
      "frontend developer",
      "full stack developer",
    ],
  }
}
